name: "Get & Cache dependencies"
description: "Get code and cache dependencies for subsequent jobs"
input:
  caching:
    description: "Enable caching of dependencies"
    required: false
    default: "true"
runs:
  using: "composite"
  steps:
    - name: Cache dependencies
      if: inputs.caching == 'true'
      id: cache
      uses: actions/cache@v4
      with:
        path: node_modules
        key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
    - name: Install dependencies
      if: steps.cache.outputs.cache-hit != 'true' || inputs.caching == 'false'
      run: npm ci
      shell: bash
