name: "Get & Cache dependencies"
description: "Get code and cache dependencies for subsequent jobs"
inputs:
  caching:
    description: "Enable caching of dependencies"
    required: false
    default: "true"
outputs:
  used-cache:
    description: "Indicates if the cache was hit"
    value: ${{ steps.install.outputs.used-cache }}
runs:
  using: "composite"
  steps:
    - name: Cache dependencies
      if: inputs.caching == 'true'
      id: cache
      uses: actions/cache@v4
      with:
        path: node_modules
        key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
    - name: Install dependencies
      id: install
      if: steps.cache.outputs.cache-hit != 'true' || inputs.caching == 'false'
      run: |
        npm ci
        echo "used-cache='${{ inputs.caching }}'" >> "$GITHUB_OUTPUT"
      shell: bash
